using System.Text;

namespace Vorotex.K15.StatusLab;

internal sealed class NotificationRuleDraftOptions
{
    public string RuleId { get; set; } = string.Empty;
    public bool IncludeTitleCondition { get; set; }
    public NotificationPriority Priority { get; set; } = NotificationPriority.Normal;
    public NotificationBehavior Behavior { get; set; } = NotificationBehavior.Pulse;
    public double MaxDurationSeconds { get; set; } = 60;
    public NotificationVisualConfig Display { get; set; } = new();
}

internal static class NotificationRuleDraftBuilder
{
    public static string Build(WindowsNotificationObservation observation, bool includeTitleCondition = false) =>
        Build(observation, new NotificationRuleDraftOptions { IncludeTitleCondition = includeTitleCondition });

    public static string Build(WindowsNotificationObservation observation, NotificationRuleDraftOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);

        var id = string.IsNullOrWhiteSpace(options.RuleId)
            ? BuildRuleId(observation.AppName, observation.PackageFamilyName, observation.AppUserModelId)
            : options.RuleId.Trim();

        var match = BuildMatch(observation, options.IncludeTitleCondition);
        var display = CloneDisplay(options.Display);
        var rule = new NotificationRule
        {
            Id = id,
            Enabled = true,
            Priority = options.Priority,
            Behavior = options.Behavior,
            MaxDurationSeconds = options.MaxDurationSeconds,
            Match = match,
            Display = display
        };

        var validation = NotificationRulesConfig.CreateDefault();
        validation.Rules.Add(rule);
        validation.Validate();

        var b = new StringBuilder();
        b.AppendLine("# Generated by VOROTEX K15 Notification Learning Lab");
        b.AppendLine("# Review before adding to notifications.toml.");
        if (options.IncludeTitleCondition && !string.IsNullOrWhiteSpace(observation.Title))
            b.AppendLine("# NOTE: this draft persists the selected notification title as a match condition.");
        else
            b.AppendLine("# Privacy-safe default: title/body content is NOT persisted in this draft.");
        b.AppendLine();
        b.AppendLine("[[rules]]");
        b.AppendLine($"id = \"{Escape(rule.Id)}\"");
        b.AppendLine("enabled = true");
        b.AppendLine($"priority = \"{PriorityName(rule.Priority)}\"");
        b.AppendLine($"behavior = \"{BehaviorName(rule.Behavior)}\"");
        b.AppendLine($"max_duration_seconds = {Format(rule.MaxDurationSeconds)}");
        b.AppendLine();
        b.AppendLine("[rules.match]");

        if (!string.IsNullOrWhiteSpace(match.PackageFamilyName))
            b.AppendLine($"package_family_name = \"{Escape(match.PackageFamilyName)}\"");
        else if (!string.IsNullOrWhiteSpace(match.AppUserModelId))
            b.AppendLine($"app_user_model_id = \"{Escape(match.AppUserModelId)}\"");
        else if (!string.IsNullOrWhiteSpace(match.AppName))
            b.AppendLine($"app_name = \"{Escape(match.AppName)}\"");
        else
            throw new InvalidDataException("Selected notification has no stable application identity for a safe rule draft.");

        if (match.TitleContains.Length > 0)
            b.AppendLine($"title_contains = [\"{Escape(match.TitleContains[0])}\"]");
        else
            b.AppendLine("title_contains = []");

        b.AppendLine("body_contains = []");
        b.AppendLine("regex = \"\"");
        b.AppendLine();
        b.AppendLine("[rules.display]");
        b.AppendLine($"effect = \"{Escape(display.Effect)}\"");
        b.AppendLine($"color_mode = \"{ColorModeName(display.ColorMode)}\"");
        b.AppendLine($"color = \"{Escape(display.Color)}\"");
        b.AppendLine($"brightness = {display.Brightness}");
        b.AppendLine($"speed = {display.Speed}");
        b.AppendLine($"direction = {display.Direction}");
        b.AppendLine($"duration_seconds = {Format(display.DurationSeconds)}");
        return b.ToString();
    }

    internal static string BuildRuleId(string appName, string packageFamilyName, string appUserModelId)
    {
        var seed = FirstNonEmpty(appName, packageFamilyName, appUserModelId, "notification");
        var b = new StringBuilder();
        var previousDash = false;
        foreach (var c in seed.Trim().ToLowerInvariant())
        {
            if (char.IsLetterOrDigit(c))
            {
                b.Append(c);
                previousDash = false;
            }
            else if (!previousDash && b.Length > 0)
            {
                b.Append('-');
                previousDash = true;
            }

            if (b.Length >= 48)
                break;
        }

        var value = b.ToString().Trim('-');
        return string.IsNullOrWhiteSpace(value) ? "notification" : value;
    }

    private static NotificationRuleMatch BuildMatch(WindowsNotificationObservation observation, bool includeTitleCondition)
    {
        var match = new NotificationRuleMatch();
        if (!string.IsNullOrWhiteSpace(observation.PackageFamilyName))
            match.PackageFamilyName = observation.PackageFamilyName;
        else if (!string.IsNullOrWhiteSpace(observation.AppUserModelId))
            match.AppUserModelId = observation.AppUserModelId;
        else if (!string.IsNullOrWhiteSpace(observation.AppName))
            match.AppName = observation.AppName;
        else
            throw new InvalidDataException("Selected notification has no stable application identity for a safe rule draft.");

        if (includeTitleCondition && !string.IsNullOrWhiteSpace(observation.Title))
            match.TitleContains = [observation.Title.Trim()];
        return match;
    }

    private static NotificationVisualConfig CloneDisplay(NotificationVisualConfig source) => new()
    {
        Effect = source.Effect,
        ColorMode = source.ColorMode,
        Color = source.Color,
        Brightness = source.Brightness,
        Speed = source.Speed,
        Direction = source.Direction,
        DurationSeconds = source.DurationSeconds
    };

    private static string PriorityName(NotificationPriority priority) => priority switch
    {
        NotificationPriority.Low => "low",
        NotificationPriority.Normal => "normal",
        NotificationPriority.High => "high",
        NotificationPriority.Critical => "critical",
        _ => "normal"
    };

    private static string BehaviorName(NotificationBehavior behavior) => behavior switch
    {
        NotificationBehavior.Pulse => "pulse",
        NotificationBehavior.WhilePresent => "while_present",
        NotificationBehavior.UntilAcknowledged => "until_acknowledged",
        _ => "pulse"
    };

    private static string ColorModeName(NotificationColorMode mode) => mode switch
    {
        NotificationColorMode.Custom => "custom",
        NotificationColorMode.CustomPlusProfile => "custom_plus_profile",
        _ => "custom"
    };

    private static string Format(double value) => value.ToString("0.###", System.Globalization.CultureInfo.InvariantCulture);

    private static string FirstNonEmpty(params string[] values) =>
        values.First(value => !string.IsNullOrWhiteSpace(value));

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
             .Replace("\"", "\\\"", StringComparison.Ordinal)
             .Replace("\r", " ", StringComparison.Ordinal)
             .Replace("\n", " ", StringComparison.Ordinal);
}
