using System.Text;

namespace Vorotex.K15.StatusLab;

internal static class NotificationRuleDraftBuilder
{
    public static string Build(WindowsNotificationObservation observation, bool includeTitleCondition = false)
    {
        var id = BuildRuleId(observation.AppName, observation.PackageFamilyName, observation.AppUserModelId);
        var b = new StringBuilder();
        b.AppendLine("# Generated by VOROTEX K15 Notification Learning Lab");
        b.AppendLine("# Review before adding to notifications.toml.");
        if (includeTitleCondition && !string.IsNullOrWhiteSpace(observation.Title))
            b.AppendLine("# NOTE: this draft persists the selected notification title as a match condition.");
        else
            b.AppendLine("# Privacy-safe default: title/body content is NOT persisted in this draft.");
        b.AppendLine();
        b.AppendLine("[[rules]]");
        b.AppendLine($"id = \"{Escape(id)}\"");
        b.AppendLine("enabled = true");
        b.AppendLine("priority = \"normal\"");
        b.AppendLine("behavior = \"pulse\"");
        b.AppendLine("max_duration_seconds = 60");
        b.AppendLine();
        b.AppendLine("[rules.match]");

        var identityWritten = false;
        if (!string.IsNullOrWhiteSpace(observation.PackageFamilyName))
        {
            b.AppendLine($"package_family_name = \"{Escape(observation.PackageFamilyName)}\"");
            identityWritten = true;
        }
        else if (!string.IsNullOrWhiteSpace(observation.AppUserModelId))
        {
            b.AppendLine($"app_user_model_id = \"{Escape(observation.AppUserModelId)}\"");
            identityWritten = true;
        }
        else if (!string.IsNullOrWhiteSpace(observation.AppName))
        {
            b.AppendLine($"app_name = \"{Escape(observation.AppName)}\"");
            identityWritten = true;
        }

        if (!identityWritten)
            throw new InvalidDataException("Selected notification has no stable application identity for a safe rule draft.");

        if (includeTitleCondition && !string.IsNullOrWhiteSpace(observation.Title))
            b.AppendLine($"title_contains = [\"{Escape(observation.Title.Trim())}\"]");
        else
            b.AppendLine("title_contains = []");

        b.AppendLine("body_contains = []");
        b.AppendLine("regex = \"\"");
        b.AppendLine();
        b.AppendLine("[rules.display]");
        b.AppendLine("effect = \"single_color_breathing\"");
        b.AppendLine("color_mode = \"custom\"");
        b.AppendLine("color = \"#FFFFFF\"");
        b.AppendLine("brightness = 6");
        b.AppendLine("speed = 7");
        b.AppendLine("direction = 0");
        b.AppendLine("duration_seconds = 6");
        return b.ToString();
    }

    internal static string BuildRuleId(string appName, string packageFamilyName, string appUserModelId)
    {
        var seed = FirstNonEmpty(appName, packageFamilyName, appUserModelId, "notification");
        var b = new StringBuilder();
        var previousDash = false;
        foreach (var c in seed.Trim().ToLowerInvariant())
        {
            if (char.IsLetterOrDigit(c))
            {
                b.Append(c);
                previousDash = false;
            }
            else if (!previousDash && b.Length > 0)
            {
                b.Append('-');
                previousDash = true;
            }

            if (b.Length >= 48)
                break;
        }

        var value = b.ToString().Trim('-');
        return string.IsNullOrWhiteSpace(value) ? "notification" : value;
    }

    private static string FirstNonEmpty(params string[] values) =>
        values.First(value => !string.IsNullOrWhiteSpace(value));

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
             .Replace("\"", "\\\"", StringComparison.Ordinal)
             .Replace("\r", " ", StringComparison.Ordinal)
             .Replace("\n", " ", StringComparison.Ordinal);
}
