[CmdletBinding()]
param(
  [Parameter(Mandatory)][ValidateSet('PREPARE','ARM','VERIFY_DISABLE','ROLLBACK')][string]$Mode,
  [string]$StateRoot = (Join-Path ($env:LOCALAPPDATA ?? [Environment]::GetFolderPath('LocalApplicationData')) 'VorotexK15\app\codex-done-r5-live'),
  [int]$TimeoutSeconds = 30,
  [switch]$WhatIf
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$RepoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..\..\..'))
$BridgeRoot = Join-Path $RepoRoot 'status-lab\research\codex-stdio-bridge'
$Activation = Join-Path $BridgeRoot 'production\Activate-CodexBridge.ps1'
$Diagnostic = Join-Path $RepoRoot 'status-lab\research\codex-done-r5\src\r5-diagnostic.mjs'
$Journal = Join-Path ($env:LOCALAPPDATA ?? [Environment]::GetFolderPath('LocalApplicationData')) 'VOROTEX\K15 Status Lab\events.jsonl'
$StateRoot = [IO.Path]::GetFullPath($StateRoot); $State = Join-Path $StateRoot 'state.json'; $Manifest = Join-Path $StateRoot 'production-manifest.json'; $Result = Join-Path $StateRoot 'result.txt'
$Allowed = 'timestampUtc','source','event','sessionId','threadId','turnId','terminalStatus','previousState','currentState','reason','correlationResult'
function Fail([string]$m) { throw [InvalidOperationException]::new($m) }
function Atomic([string]$p,$v) { New-Item -Path (Split-Path $p) -ItemType Directory -Force|Out-Null; $t="$p.$PID.tmp"; try{$v|ConvertTo-Json -Depth 12|Set-Content $t -Encoding UTF8;Move-Item $t $p -Force}finally{if(Test-Path $t){Remove-Item $t -Force -ErrorAction SilentlyContinue}} }
function Snapshot { $h=[ordered]@{}; foreach($n in 'CODEX_CLI_PATH','CODEX_BRIDGE_NODE_PATH','CODEX_BRIDGE_WRAPPER_PATH','CODEX_BRIDGE_CHILD_PATH','CODEX_BRIDGE_CHILD_SHA256','CODEX_BRIDGE_APPROVAL_SINK_PATH'){$v=[Environment]::GetEnvironmentVariable($n,'User');$h[$n]=[ordered]@{present=($null -ne $v);value=$v}}; $h }
function Restore($h) { foreach($n in $h.PSObject.Properties.Name){$x=$h.$n;if($x.present){[Environment]::SetEnvironmentVariable($n,[string]$x.value,'User')}else{[Environment]::SetEnvironmentVariable($n,$null,'User')}} }
function Homes { $u=[Environment]::GetFolderPath('UserProfile'); $p=@([Environment]::GetEnvironmentVariable('CODEX_HOME'),(Join-Path $u '.codex'),(Join-Path $u '.codex-agentloop'))+(Get-ChildItem $u -Directory -Filter '.codex-*' -ErrorAction SilentlyContinue|ForEach-Object FullName); @($p|Where-Object {$_ -and (Test-Path $_ -PathType Container)}|ForEach-Object {[IO.Path]::GetFullPath($_)}|Sort-Object -Unique) }
function HookHealth($homes) { $logger=Join-Path ($env:LOCALAPPDATA ?? [Environment]::GetFolderPath('LocalApplicationData')) 'VorotexK15\app\hooks\codex-hook-logger.ps1';$req='UserPromptSubmit','PermissionRequest','PreToolUse','PostToolUse','Stop','SessionEnd';$bad=@();if(!(Test-Path $logger -PathType Leaf)){$bad+='stable logger missing'};foreach($home in $homes){$p=Join-Path $home 'hooks.json';if(!(Test-Path $p -PathType Leaf)){$bad+="$home hooks.json missing";continue};try{$j=Get-Content $p -Raw|ConvertFrom-Json}catch{$bad+="$home malformed hooks.json";continue};foreach($e in $req){$h=@($j.hooks.$e|ForEach-Object hooks|ForEach-Object {$_}|Where-Object {([string]($_.commandWindows ?? $_.command ?? '')).Contains('codex-hook-logger.ps1')});if($h.Count -ne 1){$bad+="$home $e handler count=$($h.Count)"}};foreach($x in $j.hooks.PSObject.Properties){if($req -notcontains $x.Name -and @($x.Value|ForEach-Object hooks|Where-Object {([string]($_.commandWindows ?? $_.command ?? '')).Contains('codex-hook-logger.ps1')}).Count){$bad+="$home stale event $($x.Name)"}}};,$bad }
function Desktop { $pkgs=@(Get-AppxPackage -Name '*Codex*' -ErrorAction SilentlyContinue);$files=@($pkgs|ForEach-Object {Get-ChildItem $_.InstallLocation -Filter codex.exe -File -Recurse -ErrorAction SilentlyContinue}|Sort-Object FullName -Unique);if($files.Count -ne 1){Fail "Codex Desktop child not uniquely proven count=$($files.Count)"};$p=@($pkgs|Where-Object {$files[0].FullName.StartsWith($_.InstallLocation,[StringComparison]::OrdinalIgnoreCase)});if($p.Count -ne 1){Fail 'Codex package identity ambiguous'};[pscustomobject]@{childPath=$files[0].FullName;childSha256=(Get-FileHash $files[0].FullName -Algorithm SHA256).Hash.ToLowerInvariant();version=[string]$p[0].Version;installLocation=$p[0].InstallLocation;family=[string]$p[0].PackageFamilyName} }
function SelectEvent($e) {
  if($e.source -eq 'codex_stdio_bridge' -and $e.event -eq 'turn_completed') { return $e }
  if($e.source -eq 'state_normalizer' -and $e.event -eq 'session_state_changed') { return $e }
  $o=[ordered]@{}; foreach($n in $Allowed){if($null -ne $e.$n -and [string]$e.$n){$o[$n]=[string]$e.$n}}; [pscustomobject]$o
}
function OutResult($h) { $h.GetEnumerator()|Sort-Object Name|ForEach-Object {"$($_.Key)=$($_.Value)"} }
New-Item -Path $StateRoot -ItemType Directory -Force|Out-Null
if($Mode -eq 'PREPARE') {
  $root=(git -C $RepoRoot rev-parse --show-toplevel).Trim();$head=(git -C $RepoRoot rev-parse HEAD).Trim();$origin=(git -C $RepoRoot rev-parse origin/main).Trim()
  if(([IO.Path]::GetFullPath($root) -ine $RepoRoot) -or ($head -ne $origin) -or ((git -C $RepoRoot status --porcelain=v1).Trim())){Fail 'post-merge source identity is not clean HEAD==origin/main'}
  if(!(Test-Path $Activation -PathType Leaf) -or !(Test-Path $Diagnostic -PathType Leaf)){Fail 'accepted sources missing'}
  $homes=@(Homes);$bad=HookHealth $homes;if(($homes.Count -lt 2) -or ($bad.Count)){Fail "canonical hook health blocked: $($bad -join '; ')"};$node=(Get-Command node -ErrorAction Stop).Source;$d=Desktop
  $out=Join-Path $StateRoot 'artifacts';New-Item $out -ItemType Directory -Force|Out-Null;& dotnet publish (Join-Path $BridgeRoot 'windows-adapter\K15.CodexBridge.WindowsAdapter.csproj') -c Release -r win-x64 --self-contained false -o (Join-Path $out 'adapter')|Out-Null;if($LASTEXITCODE){Fail 'adapter publish failed'};& dotnet publish (Join-Path $RepoRoot 'status-lab\Vorotex.K15.StatusLab.csproj') -c Release -r win-x64 --self-contained true -o (Join-Path $out 'tray')|Out-Null;if($LASTEXITCODE){Fail 'tray publish failed'}
  $m=[ordered]@{schema='k15-codex-bridge/production-manifest-v1';mainSha=$head;adapterPath=(Join-Path $out 'adapter\K15.CodexBridge.WindowsAdapter.exe');nodePath=$node;wrapperPath=(Join-Path $BridgeRoot 'src\approval-wrapper.mjs');transparentWrapperPath=(Join-Path $BridgeRoot 'src\transparent-wrapper.mjs');bridgeCorePath=(Join-Path $BridgeRoot 'src\bridge-core.mjs');childPath=$d.childPath;approvalSinkPath=$Journal;desktopVersion=$d.version;desktopInstallLocation=$d.installLocation;desktopPackageFamily=$d.family;trayPath=(Join-Path $out 'tray\Vorotex.K15.StatusTray.exe')};foreach($n in 'adapterPath','nodePath','wrapperPath','transparentWrapperPath','bridgeCorePath','childPath','trayPath'){$m[($n-replace 'Path$','Sha256')]=(Get-FileHash $m[$n] -Algorithm SHA256).Hash.ToLowerInvariant()};Atomic $Manifest $m;& $Activation -Mode Validate -ManifestPath $Manifest|Out-Null;if($LASTEXITCODE){Fail 'activation Validate failed'}
  Atomic $State ([ordered]@{schema='k15-codex-done-r5-live/v3';mainSha=$head;manifestPath=$Manifest;machine=[ordered]@{CODEX_CLI_PATH=[Environment]::GetEnvironmentVariable('CODEX_CLI_PATH','Machine')};user=(Snapshot);homes=$homes;eventsPath=$Journal;offset=0;permanentTrayRunning=([bool](Get-Process -Name Vorotex.K15.StatusTray -ErrorAction SilentlyContinue))});OutResult @{STATUS='PASS';CANARY_PREPARED='YES';MAIN_SHA=$head;ENV_MUTATION='NO';HOOK_MUTATION='NO';NEXT_ACTION='CLOSE_CODEX_COMPLETELY_THEN_RUN_ARM'};exit
}
$s=if(Test-Path $State){Get-Content $State -Raw|ConvertFrom-Json}else{$null};if(!$s){Fail 'PREPARE state missing'};if([string]([Environment]::GetEnvironmentVariable('CODEX_CLI_PATH','Machine')) -ne [string]$s.machine.CODEX_CLI_PATH){Fail 'Machine environment changed'}
if($Mode -eq 'ARM') {if(Get-Process -Name Codex,codex,K15.CodexBridge.WindowsAdapter -ErrorAction SilentlyContinue){Fail 'relevant process is running'};if(!(Test-Path $Journal -PathType Leaf)){Fail 'real journal missing'};$offset=(Get-Item $Journal).Length;Atomic $State ([ordered]@{schema=$s.schema;mainSha=$s.mainSha;manifestPath=$s.manifestPath;machine=$s.machine;user=$s.user;homes=$s.homes;eventsPath=$s.eventsPath;offset=$offset;permanentTrayRunning=$s.permanentTrayRunning;armed=$true});& $Activation -Mode Validate -ManifestPath $Manifest|Out-Null;if($LASTEXITCODE){Fail 'activation Validate failed'};if($WhatIf){OutResult @{STATUS='PASS';WHATIF='YES';JOURNAL_OFFSET=$offset};exit};$m=Get-Content $Manifest -Raw|ConvertFrom-Json;if(!$s.permanentTrayRunning){Start-Process $m.trayPath -WorkingDirectory (Split-Path $m.trayPath)};& $Activation -Mode Enable -ManifestPath $Manifest|Out-Null;if($LASTEXITCODE){Fail 'activation Enable failed'};Start-Process "shell:AppsFolder\$($m.desktopPackageFamily)!App";$deadline=[Diagnostics.Stopwatch]::StartNew();do{$adapter=Get-Process -Name K15.CodexBridge.WindowsAdapter -ErrorAction SilentlyContinue;$child=@(Get-CimInstance Win32_Process -Filter "Name='codex.exe'"|Where-Object {$_.ExecutablePath -and [IO.Path]::GetFullPath($_.ExecutablePath) -ieq [IO.Path]::GetFullPath($m.childPath)});if($adapter -and $child.Count){break};Start-Sleep -Milliseconds 250}while($deadline.Elapsed.TotalSeconds -lt $TimeoutSeconds);if(!$adapter -or !$child.Count){Fail 'ordinary Desktop route evidence missing'};OutResult @{STATUS='PASS';CANARY_ARMED='YES';ADAPTER_OBSERVED='PASS';PINNED_CHILD_OBSERVED='PASS';APP_SERVER_ROUTE_OBSERVED='PASS';NEXT_ACTION='PERFORM_ONE_R5_CANARY_TURN_THEN_CLOSE_CODEX_AND_RUN_VERIFY_DISABLE'};exit}
if($Mode -eq 'VERIFY_DISABLE') {if(!(Test-Path $Journal -PathType Leaf)){Fail 'real journal missing'};$length=[int64](Get-Item $Journal).Length;if($length -lt [int64]$s.offset){Fail 'journal rotated below recorded offset'};$bytes=[IO.File]::ReadAllBytes($Journal);$delta=if($s.offset -ge $bytes.Length){''}else{[Text.Encoding]::UTF8.GetString($bytes[[int]$s.offset..($bytes.Length-1)])};if($delta.Length -gt 1048576){Fail 'journal delta exceeds 1 MiB'};$events=@();foreach($line in $delta -split "`r?`n"){try{$e=$line|ConvertFrom-Json}catch{continue};if(($e.source -eq 'codex_stdio_bridge' -and $e.event -eq 'turn_completed') -or ($e.source -eq 'state_normalizer' -and $e.event -eq 'session_state_changed') -or ($e.source -eq 'codex_hook' -and @('UserPromptSubmit','Stop','SessionEnd') -contains $e.event)){$events+=SelectEvent $e}};$tmp=Join-Path $StateRoot 'diagnostic-input.jsonl';$events|ForEach-Object {$_|ConvertTo-Json -Compress}|Set-Content $tmp -Encoding UTF8;$class=(& node (Join-Path $PSScriptRoot 'r5-live-diagnose.mjs') $tmp).Trim();$events|ForEach-Object {$_|ConvertTo-Json -Compress}|Set-Content (Join-Path $StateRoot 'sanitized-chronology.jsonl') -Encoding UTF8;$disable=0;& $Activation -Mode Disable -ManifestPath $Manifest|Out-Null;$disable=$LASTEXITCODE;$restore='FAIL';try{Restore $s.user;$restore='PASS'}catch{};$m=Get-Content $Manifest -Raw|ConvertFrom-Json;$r=@{TASK='K15-CODEX-DONE-R5-LIVE';MODE='VERIFY_DISABLE';MAIN_SHA=$s.mainSha;DESKTOP_VERSION=$m.desktopVersion;HOOK_HEALTH='PASS';RAW_PROTOCOL_PERSISTED='NO';USER_CONTENT_CAPTURED='NO';MACHINE_ENV_MUTATION='NO';DELTA_BYTES=$delta.Length;SANITIZED_EVENT_COUNT=$events.Count;USER_PROMPT_COUNT=@($events|? event -eq UserPromptSubmit).Count;STOP_COUNT=@($events|? event -eq Stop).Count;SESSION_END_COUNT=@($events|? event -eq SessionEnd).Count;TURN_COMPLETED_COUNT=@($events|? event -eq turn_completed).Count;SESSION_STATE_CHANGED_COUNT=@($events|? event -eq session_state_changed).Count;R5_CLASSIFICATION=$class;NO_STOP_LIVE_DONE_ACCEPTED=if($class -eq 'NO_STOP_LIVE_DONE_ACCEPTED'){'YES'}else{'NO'};STOP_AUTHORED_DONE=if($class -eq 'STOP_AUTHORED_DONE'){'YES'}else{'NO'};CORRELATION_FIX_CANDIDATE=if($class -eq 'CORRELATION_FIX_CANDIDATE'){'PROVEN'}else{'NOT_PROVEN'};ISSUE_93_ACCEPTANCE=if($class -eq 'NO_STOP_LIVE_DONE_ACCEPTED'){'YES'}else{'NO'};PRODUCTION_DISABLE=if($disable -eq 0){'PASS'}else{'FAIL'};USER_ENV_EXACT_RESTORE=$restore;PERMANENT_TRAY_RESTORED='NOT_PROVEN';STOCK_ROUTE_RESTORED='NOT_PROVEN';STATUS=if($disable -eq 0 -and $restore -eq 'PASS'){'PASS'}else{'BLOCKED'};NEXT_ACTION='REVIEW_SANITIZED_CHRONOLOGY'};Atomic $Result $r;Remove-Item $tmp -Force -ErrorAction SilentlyContinue;OutResult $r;exit}
if($Mode -eq 'ROLLBACK'){$restore='FAIL';try{& $Activation -Mode Disable -ManifestPath $Manifest|Out-Null;Restore $s.user;$restore='PASS'}catch{};OutResult @{STATUS=if($restore -eq 'PASS'){'PASS'}else{'BLOCKED'};ROLLBACK=if($restore -eq 'PASS'){'PASS'}else{'FAIL'};USER_ENV_EXACT_RESTORE=$restore;MACHINE_ENV_MUTATION='NO';HOOK_MUTATION='NO';WINDOWSAPPS_MUTATION='NO'};exit};Fail 'unsupported mode'
