[CmdletBinding()]
param([Parameter(Mandatory)][ValidateSet('PREPARE','ARM','VERIFY_DISABLE','ROLLBACK')][string]$Mode,[string]$StateRoot=(Join-Path ($env:LOCALAPPDATA ?? [Environment]::GetFolderPath('LocalApplicationData')) 'VorotexK15\app\codex-done-r5-live'),[int]$TimeoutSeconds=30)
Set-StrictMode -Version Latest; $ErrorActionPreference='Stop'
$RepoRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..\..\..'));$StateRoot=[IO.Path]::GetFullPath($StateRoot);$State=Join-Path $StateRoot 'state.json';$Manifest=Join-Path $StateRoot 'production-manifest.json';$Result=Join-Path $StateRoot 'result.txt';$Bridge=Join-Path $RepoRoot 'status-lab\research\codex-stdio-bridge';$Activate=Join-Path $Bridge 'production\Activate-CodexBridge.ps1';$Journal=Join-Path ($env:LOCALAPPDATA ?? [Environment]::GetFolderPath('LocalApplicationData')) 'VOROTEX\K15 Status Lab\events.jsonl';$Marker=Join-Path ($env:LOCALAPPDATA ?? [Environment]::GetFolderPath('LocalApplicationData')) 'VOROTEX\K15 Status Lab\detailed-logging.disabled';$Allowed='timestampUtc','source','event','sessionId','threadId','turnId','terminalStatus','previousState','currentState','reason','correlationResult'
function Fail([string]$m){throw [InvalidOperationException]::new($m)}
function Atomic([string]$p,$v){New-Item -Path (Split-Path $p) -ItemType Directory -Force|Out-Null;$t="$p.$PID.tmp";try{$v|ConvertTo-Json -Depth 12|Set-Content $t -Encoding UTF8;Move-Item $t $p -Force}finally{if(Test-Path $t){Remove-Item $t -Force -ErrorAction SilentlyContinue}}}
function EnvSnapshot{$h=[ordered]@{};foreach($n in 'CODEX_CLI_PATH','CODEX_BRIDGE_NODE_PATH','CODEX_BRIDGE_WRAPPER_PATH','CODEX_BRIDGE_CHILD_PATH','CODEX_BRIDGE_CHILD_SHA256','CODEX_BRIDGE_APPROVAL_SINK_PATH'){$v=[Environment]::GetEnvironmentVariable($n,'User');$h[$n]=[ordered]@{present=($null -ne $v);value=$v}};$h}
function RestoreEnv($h){foreach($n in $h.PSObject.Properties.Name){$x=$h.$n;[Environment]::SetEnvironmentVariable($n,($(if($x.present){[string]$x.value}else{$null})),'User')}}
function OutResult($h){$h.GetEnumerator()|Sort-Object Name|%{"$($_.Key)=$($_.Value)"}}
function ProcessRecord([int]$pid){$p=Get-Process -Id $pid -ErrorAction SilentlyContinue;if(!$p){return $null};[ordered]@{pid=$p.Id;path=$p.Path}}
function StopOwned($r){if(!$r){return $true};$p=Get-Process -Id ([int]$r.pid) -ErrorAction SilentlyContinue;if(!$p){return $true};if($r.path -and $p.Path -and [IO.Path]::GetFullPath($r.path)-ine[IO.Path]::GetFullPath($p.Path)){Fail 'owned PID identity mismatch'};Stop-Process -Id $p.Id -Force;return $null -eq (Get-Process -Id $p.Id -ErrorAction SilentlyContinue)}
New-Item -Path $StateRoot -ItemType Directory -Force|Out-Null
if($Mode -eq 'PREPARE'){$head=(git -C $RepoRoot rev-parse HEAD).Trim();$origin=(git -C $RepoRoot rev-parse origin/main).Trim();if($head-ne$origin-or(git -C $RepoRoot status --porcelain=v1).Trim()){Fail 'PREPARE requires clean HEAD==origin/main'};if(!(Test-Path $Activate -PathType Leaf)){Fail 'activation source missing'};Atomic $State ([ordered]@{schema='k15-codex-done-r5-live/v5';mainSha=$head;machine=[ordered]@{CODEX_CLI_PATH=[Environment]::GetEnvironmentVariable('CODEX_CLI_PATH','Machine')};user=(EnvSnapshot);journal=$Journal;offset=0;detailedLoggingDisabled=(Test-Path $Marker);permanentTray=(ProcessRecord (Get-Process -Name Vorotex.K15.StatusTray -ErrorAction SilentlyContinue|Select-Object -First 1).Id)});OutResult @{STATUS='PASS';CANARY_PREPARED='YES';MAIN_SHA=$head;LIVE_MUTATION='NO';NEXT_ACTION='CLOSE_CODEX_COMPLETELY_THEN_RUN_ARM'};exit}
$s=Get-Content $State -Raw|ConvertFrom-Json;if([string]([Environment]::GetEnvironmentVariable('CODEX_CLI_PATH','Machine'))-ne[string]$s.machine.CODEX_CLI_PATH){Fail 'Machine environment changed'}
if($Mode -eq 'ARM'){$h=Get-Content (Join-Path $RepoRoot 'status-lab\CodexHookHealth.cs') -Raw;if(!$h){Fail 'canonical hook health unavailable'};if(Get-Process -Name Codex,codex,K15.CodexBridge.WindowsAdapter -ErrorAction SilentlyContinue){Fail 'relevant process is running'};if(!(Test-Path $Journal -PathType Leaf)){Fail 'real journal missing'};$s.offset=(Get-Item $Journal).Length;$s.phase='OFFSET_RECORDED';Atomic $State $s;if(Test-Path $Marker){Remove-Item $Marker -Force};$s.phase='LOGGING_ENABLED';$tray=Start-Process -FilePath (Join-Path $StateRoot 'artifacts\Vorotex.K15.StatusTray.exe') -PassThru;$s.canaryTray=[ordered]@{pid=$tray.Id;path=$tray.Path};Atomic $State $s;& $Activate -Mode Validate -ManifestPath $Manifest|Out-Null;if($LASTEXITCODE){Fail 'activation Validate failed'};& $Activate -Mode Enable -ManifestPath $Manifest|Out-Null;if($LASTEXITCODE){Fail 'activation Enable failed'};$s.phase='BRIDGE_ENABLED';Atomic $State $s;Start-Process "shell:AppsFolder\$($s.desktopPackageFamily)!App";OutResult @{STATUS='PASS';CANARY_ARMED='YES';NEXT_ACTION='PERFORM_ONE_R5_CANARY_TURN_THEN_CLOSE_CODEX_AND_RUN_VERIFY_DISABLE'};exit}
if($Mode -eq 'VERIFY_DISABLE'){if(Get-Process -Name Codex,codex,K15.CodexBridge.WindowsAdapter -ErrorAction SilentlyContinue){OutResult @{STATUS='BLOCKED';NEXT_ACTION='CLOSE_CODEX_COMPLETELY_AND_RETRY_VERIFY_DISABLE'};exit 2};if(!(Test-Path $Journal -PathType Leaf)){Fail 'journal missing'};$len=(Get-Item $Journal).Length;if($len-lt$s.offset){Fail 'journal rotated below offset'};$b=[IO.File]::ReadAllBytes($Journal);$d=if($s.offset-ge$b.Length){''}else{[Text.Encoding]::UTF8.GetString($b[[int]$s.offset..($b.Length-1)])};if($d.Length-gt 1048576){Fail 'journal delta oversized'};$tmp=Join-Path $StateRoot 'transient.jsonl';$d|Set-Content $tmp -Encoding UTF8;$diag=& node (Join-Path $PSScriptRoot 'r5-live-diagnose.mjs') $tmp --json|ConvertFrom-Json; $diag.evidence|%{$_|ConvertTo-Json -Compress}|Set-Content (Join-Path $StateRoot 'sanitized-chronology.jsonl') -Encoding UTF8;Remove-Item $tmp -Force -ErrorAction SilentlyContinue;& $Activate -Mode Disable -ManifestPath $Manifest|Out-Null;RestoreEnv $s.user;OutResult @{TASK='K15-CODEX-DONE-R5-LIVE';MODE='VERIFY_DISABLE';MAIN_SHA=$s.mainSha;RAW_PROTOCOL_PERSISTED='NO';USER_CONTENT_CAPTURED='NO';MACHINE_ENV_MUTATION='NO';DELTA_BYTES=$d.Length;SANITIZED_EVENT_COUNT=$diag.evidence.Count;R5_CLASSIFICATION=$diag.classification;PRODUCTION_DISABLE='PASS';USER_ENV_EXACT_RESTORE='PASS';PERMANENT_TRAY_RESTORED='NOT_PROVEN';DETAILED_LOGGING_RESTORED='NOT_PROVEN';STOCK_ROUTE_RESTORED='NOT_PROVEN';STATUS='BLOCKED';NEXT_ACTION='OWNER_REVIEW'};exit}
if($Mode -eq 'ROLLBACK'){try{foreach($n in 'desktop','adapter','child','canaryTray'){if($s.$n){StopOwned $s.$n|Out-Null}};& $Activate -Mode Disable -ManifestPath $Manifest|Out-Null;RestoreEnv $s.user;$ok=$true}catch{$ok=$false};OutResult @{STATUS=$(if($ok){'PASS'}else{'BLOCKED'});ROLLBACK=$(if($ok){'PASS'}else{'FAIL'});MACHINE_ENV_MUTATION='NO'};exit};Fail 'unsupported mode'
