Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-R5Json($Path, $Value) {
    $dir = Split-Path -Parent $Path; New-Item -Path $dir -ItemType Directory -Force | Out-Null
    $tmp = "$Path.$PID.tmp"
    try { $Value | ConvertTo-Json -Depth 20 | Set-Content -LiteralPath $tmp -Encoding UTF8; Move-Item -LiteralPath $tmp -Destination $Path -Force }
    finally { if (Test-Path $tmp) { Remove-Item $tmp -Force -ErrorAction SilentlyContinue } }
}
function Get-R5State($Provider) { if (!(Test-Path $Provider.StatePath)) { throw 'state.json is missing' }; Get-Content $Provider.StatePath -Raw | ConvertFrom-Json }
function Save-R5State($Provider, $State) { Write-R5Json $Provider.StatePath $State }
function Get-R5Property($Object, [string]$Name) { $p = $Object.PSObject.Properties[$Name]; if ($p) { return $p.Value }; return $null }
function Set-R5Property($Object, [string]$Name, $Value) { $p = $Object.PSObject.Properties[$Name]; if ($p) { $p.Value = $Value } else { $Object | Add-Member NoteProperty $Name $Value } }
function New-R5Result($Map) { $Map.GetEnumerator() | Sort-Object Name | ForEach-Object { "$($_.Key)=$($_.Value)" } }
function Test-R5HookHealth([string]$LocalAppData) {
    $user = [Environment]::GetFolderPath('UserProfile'); $homes = @((Join-Path $user '.codex'), (Join-Path $user '.codex-agentloop')); if ($env:CODEX_HOME) { $homes += $env:CODEX_HOME }; try { $homes += @(Get-ChildItem $user -Directory -Filter '.codex-*' -ErrorAction Stop | % FullName) } catch { }
    $stable = [IO.Path]::GetFullPath((Join-Path $LocalAppData 'VorotexK15\app\hooks\codex-hook-logger.ps1')); $required = 'UserPromptSubmit','PermissionRequest','PreToolUse','PostToolUse','Stop','SessionEnd'; $bad = @(); if (!(Test-Path $stable -PathType Leaf)) { $bad += 'stable logger missing' }
    foreach ($home in $homes | Sort-Object -Unique) { if (!(Test-Path $home -PathType Container)) { continue }; $path = Join-Path $home 'hooks.json'; if (!(Test-Path $path -PathType Leaf)) { $bad += "$home hooks.json missing"; continue }; try { $json = Get-Content $path -Raw | ConvertFrom-Json } catch { $bad += "$home malformed hooks.json"; continue }; foreach ($property in @($json.hooks.PSObject.Properties)) { if ($required -notcontains $property.Name) { $stale = @($property.Value | % hooks | ? { ([string]($_.commandWindows ?? $_.command_windows ?? $_.command ?? '')).Contains('codex-hook-logger.ps1') }); if ($stale.Count) { $bad += "$home stale Status Lab event $($property.Name)" } } }; foreach ($event in $required) { $matches = @($json.hooks.$event | % hooks | ? { ([string]($_.commandWindows ?? $_.command_windows ?? $_.command ?? '')).Contains('codex-hook-logger.ps1') }); if ($matches.Count -ne 1) { $bad += "$home $event handler count=$($matches.Count)" }; foreach ($handler in $matches) { $command = [string]($handler.commandWindows ?? $handler.command_windows ?? $handler.command ?? ''); $m = [regex]::Match($command, '(?i)-File\s+(?:"([^"]+)"|(\S+))'); $target = if ($m.Success) { if ($m.Groups[1].Success) { $m.Groups[1].Value } else { $m.Groups[2].Value } } else { '' }; if (!$target -or [IO.Path]::GetFullPath($target) -ine $stable) { $bad += "$home path drift $event" }; if ($target -match '\([^)]*\d[^)]*\)') { $bad += "$home transient numbered build path $event" } } } }
    return [pscustomobject]@{ Pass = (($bad | Sort-Object -Unique).Count -eq 0); Detail = (($bad | Sort-Object -Unique) -join '; ') }
}

function New-R5RealProvider([string]$RepoRoot, [string]$StateRoot, [int]$TimeoutSeconds) {
    $local = $env:LOCALAPPDATA ?? [Environment]::GetFolderPath('LocalApplicationData')
    $p = [pscustomobject]@{ Kind = 'Real'; RepoRoot = $RepoRoot; LocalAppData = $local; StateRoot = [IO.Path]::GetFullPath($StateRoot); StatePath = Join-Path $StateRoot 'state.json'; ManifestPath = Join-Path $StateRoot 'production-manifest.json'; TimeoutSeconds = $TimeoutSeconds; Journal = Join-Path $local 'VOROTEX\K15 Status Lab\events.jsonl'; Marker = Join-Path $local 'VOROTEX\K15 Status Lab\detailed-logging.disabled'; BridgeRoot = Join-Path $RepoRoot 'status-lab\research\codex-stdio-bridge'; Activate = Join-Path $RepoRoot 'status-lab\research\codex-stdio-bridge\production\Activate-CodexBridge.ps1' }
    $p | Add-Member ScriptMethod RepoPreflight { $head = (git -C $this.RepoRoot rev-parse HEAD).Trim(); $origin = (git -C $this.RepoRoot rev-parse origin/main).Trim(); if ($head -ne $origin -or (git -C $this.RepoRoot status --porcelain=v1).Trim()) { throw 'PREPARE requires clean HEAD==origin/main' }; return $head }
    $p | Add-Member ScriptMethod HookHealth { return Test-R5HookHealth $this.LocalAppData }
    $p | Add-Member ScriptMethod Publish {
        $out = Join-Path $this.StateRoot 'artifacts'; New-Item $out -ItemType Directory -Force | Out-Null
        & dotnet publish (Join-Path $this.BridgeRoot 'windows-adapter\K15.CodexBridge.WindowsAdapter.csproj') -c Release -r win-x64 --self-contained false -o (Join-Path $out 'adapter') | Out-Null; if ($LASTEXITCODE) { throw 'adapter artifact publish failed' }
        & dotnet publish (Join-Path $this.RepoRoot 'status-lab\Vorotex.K15.StatusLab.csproj') -c Release -r win-x64 --self-contained true -o (Join-Path $out 'tray') | Out-Null; if ($LASTEXITCODE) { throw 'tray artifact publish failed' }
        $packages = @(Get-AppxPackage -Name '*Codex*' -ErrorAction SilentlyContinue); $children = @($packages | ForEach-Object { Get-ChildItem $_.InstallLocation -Filter codex.exe -File -Recurse -ErrorAction SilentlyContinue } | Sort-Object FullName -Unique); if ($children.Count -ne 1) { throw "Codex child is not uniquely proven count=$($children.Count)" }
        $pkg = @($packages | Where-Object { $children[0].FullName.StartsWith($_.InstallLocation, [StringComparison]::OrdinalIgnoreCase) }); if ($pkg.Count -ne 1) { throw 'Codex package identity is ambiguous' }
        $m = [ordered]@{ schema = 'k15-codex-bridge/production-manifest-v1'; adapterPath = Join-Path $out 'adapter\K15.CodexBridge.WindowsAdapter.exe'; nodePath = (Get-Command node -ErrorAction Stop).Source; wrapperPath = Join-Path $this.BridgeRoot 'src\approval-wrapper.mjs'; transparentWrapperPath = Join-Path $this.BridgeRoot 'src\transparent-wrapper.mjs'; bridgeCorePath = Join-Path $this.BridgeRoot 'src\bridge-core.mjs'; childPath = $children[0].FullName; approvalSinkPath = $this.Journal; desktopVersion = [string]$pkg[0].Version; desktopInstallLocation = $pkg[0].InstallLocation; desktopPackageFamily = [string]$pkg[0].PackageFamilyName; trayPath = Join-Path $out 'tray\Vorotex.K15.StatusTray.exe' }
        foreach ($n in 'adapterPath','nodePath','wrapperPath','transparentWrapperPath','bridgeCorePath','childPath','trayPath') { if (!(Test-Path $m[$n] -PathType Leaf)) { throw "manifest path missing: $n" }; $m[($n -replace 'Path$','Sha256')] = (Get-FileHash $m[$n] -Algorithm SHA256).Hash.ToLowerInvariant() }; return $m
    }
    $p | Add-Member ScriptMethod Validate { & $this.Activate -Mode Validate -ManifestPath $this.ManifestPath | Out-Null; if ($LASTEXITCODE) { throw 'activation Validate failed' } }
    $p | Add-Member ScriptMethod Enable { & $this.Activate -Mode Enable -ManifestPath $this.ManifestPath | Out-Null; if ($LASTEXITCODE) { throw 'activation Enable failed' } }
    $p | Add-Member ScriptMethod Disable { & $this.Activate -Mode Disable -ManifestPath $this.ManifestPath | Out-Null; if ($LASTEXITCODE) { throw 'activation Disable failed' } }
    $p | Add-Member ScriptMethod GetPermanentTray { $q = @(Get-Process -Name Vorotex.K15.StatusTray -ErrorAction SilentlyContinue | Select-Object -First 1); if (!$q) { return [ordered]@{ running = $false; path = ''; sha256 = '' } }; return [ordered]@{ running = $true; pid = $q.Id; path = $q.Path; sha256 = (Get-FileHash $q.Path -Algorithm SHA256).Hash.ToLowerInvariant() } }
    $p | Add-Member ScriptMethod EnvSnapshot { $r = [ordered]@{}; foreach ($n in 'CODEX_CLI_PATH','CODEX_BRIDGE_NODE_PATH','CODEX_BRIDGE_WRAPPER_PATH','CODEX_BRIDGE_CHILD_PATH','CODEX_BRIDGE_CHILD_SHA256','CODEX_BRIDGE_APPROVAL_SINK_PATH') { $v = [Environment]::GetEnvironmentVariable($n,'User'); $r[$n] = [ordered]@{ present = ($null -ne $v); value = $v } }; return $r }
    $p | Add-Member ScriptMethod RestoreEnv { param($s); foreach ($n in $s.PSObject.Properties.Name) { $i = $s.$n; [Environment]::SetEnvironmentVariable($n, $(if ($i.present) { [string]$i.value } else { $null }), 'User') } }
    $p | Add-Member ScriptMethod EnvMatches { param($s); foreach ($n in $s.PSObject.Properties.Name) { $actual = [Environment]::GetEnvironmentVariable($n,'User'); if ([bool]$s.$n.present -ne ($null -ne $actual) -or ([bool]$s.$n.present -and [string]$s.$n.value -cne [string]$actual)) { return $false } }; return $true }
    $p | Add-Member ScriptMethod MachineValue { [Environment]::GetEnvironmentVariable('CODEX_CLI_PATH','Machine') }
    $p | Add-Member ScriptMethod JournalOffset { if (!(Test-Path $this.Journal -PathType Leaf)) { throw 'real journal missing' }; (Get-Item $this.Journal).Length }
    $p | Add-Member ScriptMethod JournalDelta { param($offset); $b = [IO.File]::ReadAllBytes($this.Journal); if ($b.Length -lt $offset) { throw 'journal rotated below offset' }; if ($offset -ge $b.Length) { return '' }; $d = [Text.Encoding]::UTF8.GetString($b[[int]$offset..($b.Length-1)]); if ($d.Length -gt 1048576) { throw 'journal delta oversized' }; return $d }
    $p | Add-Member ScriptMethod StartTray { param($path); return Get-ProcessIdentity (Start-Process $path -PassThru) }
    $p | Add-Member ScriptMethod StartDesktop { param($family); return Start-Process "shell:AppsFolder\$family!App" -PassThru }
    $p | Add-Member ScriptMethod Route { param($manifest); $a = @(Get-CimInstance Win32_Process -Filter "Name='K15.CodexBridge.WindowsAdapter.exe'" | Where-Object ExecutablePath -eq $manifest.adapterPath | Select-Object -First 1); $c = @(Get-CimInstance Win32_Process -Filter "Name='codex.exe'" | Where-Object ExecutablePath -eq $manifest.childPath | Select-Object -First 1); return [pscustomobject]@{ adapter = $a; child = $c } }
    $p | Add-Member ScriptMethod LiveProcesses { @((Get-Process -Name Codex,codex,K15.CodexBridge.WindowsAdapter -ErrorAction SilentlyContinue)) }
    $p | Add-Member ScriptMethod StopExact { param($r); if (!$r) { return $true }; $q = Get-Process -Id ([int]$r.pid) -ErrorAction SilentlyContinue; if (!$q) { return $true }; if ($r.path -and $q.Path -and [IO.Path]::GetFullPath($r.path) -ine [IO.Path]::GetFullPath($q.Path)) { throw 'owned process identity mismatch' }; if ($r.sha256 -and $q.Path -and (Get-FileHash $q.Path -Algorithm SHA256).Hash.ToLowerInvariant() -cne [string]$r.sha256) { throw 'owned process hash mismatch' }; Stop-Process -Id $q.Id -Force; return $null -eq (Get-Process -Id $q.Id -ErrorAction SilentlyContinue) }
    $p | Add-Member ScriptMethod MarkerExists { Test-Path $this.Marker }
    $p | Add-Member ScriptMethod SetMarker { param($exists); if ($exists -and !(Test-Path $this.Marker)) { New-Item $this.Marker -ItemType File -Force | Out-Null }; if (!$exists -and (Test-Path $this.Marker)) { Remove-Item $this.Marker -Force } }
    $p | Add-Member ScriptMethod RestoreTray { param($original); if (!$original.running) { return $true }; if (!(Test-Path $original.path -PathType Leaf)) { throw 'original permanent tray path missing' }; $q = Start-Process $original.path -PassThru; if (!$q.Path -or [IO.Path]::GetFullPath($q.Path) -ine [IO.Path]::GetFullPath($original.path)) { throw 'permanent tray identity not restored' }; return $true }
    $p | Add-Member ScriptMethod RestoreLogging { param($original); $this.SetMarker($original) ; return ($this.MarkerExists() -eq [bool]$original) }
    $p | Add-Member ScriptMethod RestoreStock { param($s); $null = $this.StartDesktop($s.desktop.packageFamily); $deadline = [DateTime]::UtcNow.AddSeconds($this.TimeoutSeconds); do { Start-Sleep -Milliseconds 250; $r = $this.Route($s.manifest); if (@($r.adapter).Count -eq 0 -and @($r.child).Count -eq 1 -and $r.child[0].ExecutablePath -eq $s.desktop.childPath -and (Get-FileHash $r.child[0].ExecutablePath -Algorithm SHA256).Hash.ToLowerInvariant() -ceq $s.desktop.childSha256) { return $true } } while ([DateTime]::UtcNow -lt $deadline); throw 'stock route proof failed' }
    $p | Add-Member ScriptMethod Diagnose { param($delta); $helper = Join-Path $this.RepoRoot 'status-lab\research\codex-done-r5\live\r5-live-diagnose.mjs'; $si = [Diagnostics.ProcessStartInfo]::new(); $si.FileName = (Get-Command node).Source; $si.Arguments = '"' + $helper + '" - --json'; $si.UseShellExecute = $false; $si.RedirectStandardInput = $true; $si.RedirectStandardOutput = $true; $si.RedirectStandardError = $true; $q = [Diagnostics.Process]::Start($si); $q.StandardInput.Write($delta); $q.StandardInput.Close(); $o = $q.StandardOutput.ReadToEnd(); $e = $q.StandardError.ReadToEnd(); $q.WaitForExit(); if ($q.ExitCode) { throw $e }; return $o | ConvertFrom-Json }
    $p
}

function New-R5FakeProvider([string]$StateRoot, [string]$Scenario = '') {
    $p = [pscustomobject]@{ Kind = 'Fake'; StateRoot = [IO.Path]::GetFullPath($StateRoot); StatePath = Join-Path $StateRoot 'state.json'; ManifestPath = Join-Path $StateRoot 'production-manifest.json'; Journal = 'fake-journal'; Scenario = $Scenario; Machine = 'machine-baseline'; Env = [ordered]@{}; Marker = $true; PermanentRunning = $true; Canaries = @{}; Activation = 'DISABLED'; HookPass = $true; RoutePass = $true; StockPass = $true; RestoreTrayPass = $true; RestoreLoggingPass = $true; RestoreEnvPass = $true; Live = $false }
    foreach ($n in 'CODEX_CLI_PATH','CODEX_BRIDGE_NODE_PATH','CODEX_BRIDGE_WRAPPER_PATH','CODEX_BRIDGE_CHILD_PATH','CODEX_BRIDGE_CHILD_SHA256','CODEX_BRIDGE_APPROVAL_SINK_PATH') { $p.Env[$n] = [ordered]@{ present = $true; value = "value-$n" } }
    if ($Scenario -match 'hook') { $p.HookPass = $false }; if ($Scenario -match 'route-timeout') { $p.RoutePass = $false }; if ($Scenario -match 'stock-fail') { $p.StockPass = $false }; if ($Scenario -match 'tray-fail') { $p.RestoreTrayPass = $false }; if ($Scenario -match 'logging-fail') { $p.RestoreLoggingPass = $false }; if ($Scenario -match 'env-fail') { $p.RestoreEnvPass = $false }; if ($Scenario -match 'tray-stopped') { $p.PermanentRunning = $false }; if ($Scenario -match 'live') { $p.Live = $true }
    $p | Add-Member ScriptMethod RepoPreflight { return 'FAKE-MAIN' }
    $p | Add-Member ScriptMethod HookHealth { return [pscustomobject]@{ Pass = $this.HookPass; Detail = $(if ($this.HookPass) { 'canonical Status Lab hook health' } else { 'hook health mismatch' }) } }
    $p | Add-Member ScriptMethod Publish { $out = Join-Path $this.StateRoot 'artifacts'; New-Item $out -ItemType Directory -Force | Out-Null; foreach ($f in 'adapter\K15.CodexBridge.WindowsAdapter.exe','tray\Vorotex.K15.StatusTray.exe') { $path = Join-Path $out $f; New-Item (Split-Path $path) -ItemType Directory -Force | Out-Null; Set-Content $path 'fake artifact' }; return [ordered]@{ schema = 'k15-codex-bridge/production-manifest-v1'; adapterPath = Join-Path $out 'adapter\K15.CodexBridge.WindowsAdapter.exe'; adapterSha256 = 'fake-adapter'; nodePath = 'fake-node'; wrapperPath = 'fake-wrapper'; transparentWrapperPath = 'fake-transparent'; bridgeCorePath = 'fake-core'; childPath = 'fake-child'; childSha256 = 'fake-child'; approvalSinkPath = 'fake-journal'; desktopVersion = 'fake-version'; desktopPackageFamily = 'fake-family'; trayPath = Join-Path $out 'tray\Vorotex.K15.StatusTray.exe'; traySha256 = 'fake-tray' } }
    $p | Add-Member ScriptMethod Validate { if ($this.Scenario -match 'validate-fail') { throw 'activation Validate failed' } }
    $p | Add-Member ScriptMethod Enable { $this.Activation = 'ENABLED' }
    $p | Add-Member ScriptMethod Disable { $this.Activation = 'DISABLED' }
    $p | Add-Member ScriptMethod GetPermanentTray { return [ordered]@{ running = $this.PermanentRunning; pid = $(if ($this.PermanentRunning) { 2001 } else { 0 }); path = 'fake-permanent-tray'; sha256 = 'fake-permanent' } }
    $p | Add-Member ScriptMethod EnvSnapshot { return $this.Env }
    $p | Add-Member ScriptMethod RestoreEnv { param($s); if (!$this.RestoreEnvPass) { throw 'fake env restore failed' }; $this.Env = $s }
    $p | Add-Member ScriptMethod EnvMatches { param($s); return $this.RestoreEnvPass }
    $p | Add-Member ScriptMethod MachineValue { return $this.Machine }
    $p | Add-Member ScriptMethod JournalOffset { return 0 }
    $p | Add-Member ScriptMethod JournalDelta { param($offset); return '' }
    $p | Add-Member ScriptMethod StartTray { param($path); $r = [ordered]@{ pid = 2002; path = $path; sha256 = 'fake-tray' }; $this.Canaries[$r.pid] = $true; return $r }
    $p | Add-Member ScriptMethod StartDesktop { param($family); return [ordered]@{ pid = 2003; path = 'fake-desktop'; sha256 = 'fake-desktop' } }
    $p | Add-Member ScriptMethod Route { param($manifest); if (!$this.RoutePass) { return [pscustomobject]@{ adapter = @(); child = @() } }; return [pscustomobject]@{ adapter = @([pscustomobject]@{ ProcessId = 2004; ExecutablePath = $manifest.adapterPath }); child = @([pscustomobject]@{ ProcessId = 2005; ExecutablePath = $manifest.childPath }) } }
    $p | Add-Member ScriptMethod LiveProcesses { if ($this.Live) { return @([pscustomobject]@{ Id = 2010 }) }; return @() }
    $p | Add-Member ScriptMethod StopExact { param($r); if ($r -and $r.pid -eq 9999) { throw 'owned process identity mismatch' }; return $true }
    $p | Add-Member ScriptMethod MarkerExists { return $this.Marker }
    $p | Add-Member ScriptMethod SetMarker { param($exists); $this.Marker = [bool]$exists }
    $p | Add-Member ScriptMethod RestoreLogging { param($original); if (!$this.RestoreLoggingPass) { throw 'fake logging restore failed' }; $this.Marker = [bool]$original; return $true }
    $p | Add-Member ScriptMethod Diagnose { param($delta); return [pscustomobject]@{ classification = 'NO_COMPLETION'; evidence = @(); cases = @() } }
    $p | Add-Member ScriptMethod RestoreTray { if (!$this.RestoreTrayPass) { throw 'fake tray restore failed' }; return $true }
    $p | Add-Member ScriptMethod RestoreStock { if (!$this.StockPass) { throw 'fake stock route failed' }; return $true }
    $p
}

function Get-ProcessIdentity([Diagnostics.Process]$Process) { if (!$Process) { return $null }; [ordered]@{ pid = $Process.Id; path = $Process.Path; sha256 = $(if ($Process.Path) { (Get-FileHash $Process.Path -Algorithm SHA256).Hash.ToLowerInvariant() } else { '' }) } }
function Invoke-R5Prepare($Provider) {
    $main = $Provider.RepoPreflight(); $health = $Provider.HookHealth(); if (!$health.Pass) { throw "hook health blocked: $($health.Detail)" }; $manifest = $Provider.Publish(); Write-R5Json $Provider.ManifestPath $manifest; $Provider.Validate(); $tray = $Provider.GetPermanentTray(); $s = [ordered]@{ schema = 'k15-codex-done-r5-live/v8'; mainSha = $main; manifestPath = $Provider.ManifestPath; manifest = $manifest; journal = $Provider.Journal; offset = 0; user = $Provider.EnvSnapshot(); machine = [ordered]@{ CODEX_CLI_PATH = $Provider.MachineValue() }; desktop = [ordered]@{ childPath = $manifest.childPath; childSha256 = $manifest.childSha256; packageFamily = $manifest.desktopPackageFamily; version = $manifest.desktopVersion }; detailedLoggingDisabled = $Provider.MarkerExists(); permanentTray = $tray; phase = 'PREPARED' }; Save-R5State $Provider $s; New-R5Result @{ STATUS = 'PASS'; CANARY_PREPARED = 'YES'; MAIN_SHA = $main; ENV_MUTATION = 'NO'; HOOK_MUTATION = 'NO' }
}
function Invoke-R5Arm($Provider) {
    $s = Get-R5State $Provider; $health = $Provider.HookHealth(); if (!$health.Pass) { throw "hook health changed before ARM: $($health.Detail)" }; if (@($Provider.LiveProcesses()).Count) { throw 'relevant process running' }; $Provider.Validate(); $s.offset = $Provider.JournalOffset(); $s.phase = 'VALIDATED'; Save-R5State $Provider $s
    if ($s.permanentTray.running) { if (!$Provider.StopExact($s.permanentTray)) { throw 'permanent tray stop not proven' } }
    $canary = $Provider.StartTray($s.manifest.trayPath); Set-R5Property $s 'canaryTray' $canary; $s.phase = 'TRAY_STARTED'; Save-R5State $Provider $s; $Provider.SetMarker($false); $Provider.Enable(); $s.phase = 'BRIDGE_ENABLED'; Save-R5State $Provider $s; Set-R5Property $s 'desktopProcess' ($Provider.StartDesktop($s.desktop.packageFamily)); $s.phase = 'DESKTOP_STARTED'; Save-R5State $Provider $s
    $route = $Provider.Route($s.manifest); if (@($route.adapter).Count -ne 1 -or @($route.child).Count -ne 1) { New-R5Result @{ STATUS = 'BLOCKED'; CANARY_ARMED = 'NO'; NEXT_ACTION = 'ROLLBACK'; ADAPTER_OBSERVED = 'NO'; PINNED_CHILD_OBSERVED = 'NO' }; return }
    Set-R5Property $s 'adapter' ([ordered]@{ pid = $route.adapter[0].ProcessId; path = $route.adapter[0].ExecutablePath; sha256 = $s.manifest.adapterSha256 }); Set-R5Property $s 'child' ([ordered]@{ pid = $route.child[0].ProcessId; path = $route.child[0].ExecutablePath; sha256 = $s.desktop.childSha256 }); $s.phase = 'ARMED'; Save-R5State $Provider $s; New-R5Result @{ STATUS = 'PASS'; CANARY_ARMED = 'YES'; ADAPTER_OBSERVED = 'YES'; PINNED_CHILD_OBSERVED = 'YES'; APP_SERVER_ROUTE_OBSERVED = 'YES' }
}
function Invoke-R5VerifyDisable($Provider) {
    $s = Get-R5State $Provider; if (@($Provider.LiveProcesses()).Count) { New-R5Result @{ STATUS = 'BLOCKED'; NEXT_ACTION = 'CLOSE_CODEX_COMPLETELY_AND_RETRY_VERIFY_DISABLE' }; return }
    try {
        if (Get-R5Property $s 'canaryTray') { $Provider.StopExact($s.canaryTray) | Out-Null }
        $delta = $Provider.JournalDelta($s.offset); $diag = $Provider.Diagnose($delta); $Provider.Disable(); $Provider.RestoreEnv($s.user); $envOk = $Provider.EnvMatches($s.user); $loggingOk = $Provider.RestoreLogging($s.detailedLoggingDisabled)
        $trayOk = $Provider.RestoreTray($s.permanentTray); $stockOk = $Provider.RestoreStock($s)
        $e = @($diag.evidence); $chronology = Join-Path $Provider.StateRoot 'sanitized-chronology.jsonl'; $e | ForEach-Object { $_ | ConvertTo-Json -Compress } | Set-Content $chronology -Encoding UTF8
        $counts = @{ USER_PROMPT_COUNT = @($e | Where-Object event -eq 'UserPromptSubmit').Count; STOP_COUNT = @($e | Where-Object event -eq 'Stop').Count; SESSION_END_COUNT = @($e | Where-Object event -eq 'SessionEnd').Count; TURN_COMPLETED_COUNT = @($e | Where-Object event -eq 'turn_completed').Count; SESSION_STATE_CHANGED_COUNT = @($e | Where-Object event -eq 'session_state_changed').Count }
        $sessions = @($e | ForEach-Object sessionId | Where-Object { $_ }); $turns = @($e | ForEach-Object turnId | Where-Object { $_ }); $statuses = @($e | ForEach-Object terminalStatus | Where-Object { $_ }); $ok = $trayOk -and $stockOk -and $loggingOk -and $envOk; $result = @{ TASK = 'K15-CODEX-DONE-R5-LIVE'; MODE = 'VERIFY_DISABLE'; MAIN_SHA = $s.mainSha; DESKTOP_VERSION = $s.desktop.version; HOOK_HEALTH = 'PASS'; RAW_PROTOCOL_PERSISTED = 'NO'; USER_CONTENT_CAPTURED = 'NO'; MACHINE_ENV_MUTATION = 'NO'; DELTA_BYTES = $delta.Length; SANITIZED_EVENT_COUNT = $e.Count; VERIFIED_SESSION_ID_LENGTH = $(if ($sessions) { ($sessions | Measure-Object Length -Maximum).Maximum } else { 0 }); VERIFIED_TURN_ID_LENGTH = $(if ($turns) { ($turns | Measure-Object Length -Maximum).Maximum } else { 0 }); TURN_COMPLETION_STATUS = $(if ($statuses) { $statuses -join ',' } else { 'NOT_EMITTED' }); CHRONOLOGY = 'SANITIZED_EVIDENCE'; R5_CLASSIFICATION = $diag.classification; NO_STOP_LIVE_DONE_ACCEPTED = $(if ($diag.classification -eq 'NO_STOP_LIVE_DONE_ACCEPTED') {'YES'} else {'NO'}); STOP_AUTHORED_DONE = $(if ($diag.classification -eq 'STOP_AUTHORED_DONE') {'YES'} else {'NO'}); CORRELATION_FIX_CANDIDATE = $(if ($diag.classification -eq 'CORRELATION_FIX_CANDIDATE') {'PROVEN'} else {'NOT_PROVEN'}); ISSUE_93_ACCEPTANCE = $(if ($diag.classification -eq 'NO_STOP_LIVE_DONE_ACCEPTED') {'YES'} else {'NO'}); PRODUCTION_DISABLE = 'PASS'; USER_ENV_EXACT_RESTORE = $(if ($envOk) {'PASS'} else {'FAIL'}); PERMANENT_TRAY_RESTORED = $(if ($trayOk) {'PASS'} else {'FAIL'}); DETAILED_LOGGING_RESTORED = $(if ($loggingOk) {'PASS'} else {'FAIL'}); STOCK_ROUTE_RESTORED = $(if ($stockOk) {'PASS'} else {'FAIL'}); STOCK_CHILD_AFTER_DISABLE = $(if ($stockOk) {'PASS'} else {'FAIL'}); ADAPTER_AFTER_DISABLE = $(if ($stockOk) {'NOT_OBSERVED'} else {'NOT_PROVEN'}); STATUS = $(if ($ok) {'PASS'} else {'BLOCKED'}); NEXT_ACTION = $(if ($ok) {'OWNER_REVIEW'} else {'ROLLBACK'}) }
        foreach ($key in $counts.Keys) { $result[$key] = $counts[$key] }; New-R5Result $result
    } catch { New-R5Result @{ STATUS = 'BLOCKED'; NEXT_ACTION = 'ROLLBACK'; PRODUCTION_DISABLE = 'FAIL'; USER_ENV_EXACT_RESTORE = 'FAIL'; PERMANENT_TRAY_RESTORED = 'FAIL'; DETAILED_LOGGING_RESTORED = 'FAIL'; STOCK_ROUTE_RESTORED = 'FAIL' } }
}
function Invoke-R5Rollback($Provider) {
    $s = Get-R5State $Provider; $fail = $false; foreach ($n in 'desktopProcess','adapter','child','canaryTray') { $r = Get-R5Property $s $n; if ($r) { try { if (!$Provider.StopExact($r)) { $fail = $true } } catch { $fail = $true } } }; try { $Provider.Disable() } catch { $fail = $true }; try { $Provider.RestoreEnv($s.user) } catch { $fail = $true }; try { $Provider.RestoreLogging($s.detailedLoggingDisabled) | Out-Null } catch { $fail = $true }; try { $Provider.RestoreTray($s.permanentTray) | Out-Null; $Provider.RestoreStock($s) | Out-Null } catch { $fail = $true }; New-R5Result @{ STATUS = $(if ($fail) {'BLOCKED'} else {'PASS'}); ROLLBACK = $(if ($fail) {'FAIL'} else {'PASS'}); USER_ENV_EXACT_RESTORE = $(if ($fail) {'FAIL'} else {'PASS'}); MACHINE_ENV_MUTATION = 'NO' }
}
Export-ModuleMember -Function New-R5RealProvider,New-R5FakeProvider,Invoke-R5Prepare,Invoke-R5Arm,Invoke-R5VerifyDisable,Invoke-R5Rollback
