using System.Text.Json;
using Vorotex.K15.LiveDashboard;
using Vorotex.K15.StatusLab;

static void Require(bool condition, string message) { if (!condition) throw new InvalidOperationException(message); }
var now = DateTimeOffset.UtcNow.ToString("o");
string Hook(string extra = "") => $"{{\"timestampUtc\":\"{now}\",\"source\":\"codex_hook\",\"event\":\"Stop\",\"sessionId\":\"s1\",\"turnId\":\"t1\"{extra}}}";
Require(EventSanitizer.Project(Hook()) is not null, "safe hook was rejected");
foreach (var bad in new[] { Hook(",\"prompt\":\"secret\""), Hook(",\"unknown\":\"secret\""), $"{{\"timestampUtc\":\"{now}\",\"source\":\"state_normalizer\",\"event\":\"session_state_changed\",\"current\":\"RUNNING\",\"reason\":\"secret\",\"correlation\":{{\"prompt\":\"secret\"}}}}", $"{{\"timestampUtc\":\"{now}\",\"source\":\"codex_stdio_bridge\",\"event\":\"turn_completed\",\"status\":\"secret\"}}" }) Require(EventSanitizer.Project(bad) is null, "adversarial content survived sanitizer");
var safe = EventSanitizer.Project($"{{\"timestampUtc\":\"{now}\",\"source\":\"codex_stdio_bridge\",\"event\":\"turn_completed\",\"status\":\"completed\",\"threadId\":\"th\",\"turnId\":\"tu\"}}")!;
var safeJson = JsonSerializer.Serialize(safe); Require(!safeJson.Contains("secret") && !safeJson.Contains("prompt"), "forbidden content reached DTO");
var root = Path.Combine(Path.GetTempPath(), "k15-live-dashboard-behavior-" + Guid.NewGuid().ToString("N")); var journal = Path.Combine(root, "events.jsonl"); Directory.CreateDirectory(root);
try {
    File.WriteAllText(journal + ".1", Hook() + Environment.NewLine); var tailer = new JournalTailer(journal, 200); Require(tailer.Snapshot().Count == 1, "archive history was not loaded");
    File.AppendAllText(journal, Hook() + "\n{malformed\n"); Require(tailer.Poll().Count == 1, "append/malformed handling failed"); var partial = Hook().TrimEnd('}'); File.AppendAllText(journal, partial); Require(tailer.Poll().Count == 0, "partial line was emitted"); File.AppendAllText(journal, "}\n"); Require(tailer.Poll().Count == 1, "partial line was not completed");
    File.WriteAllText(journal, Hook() + "\n"); Require(tailer.Poll().Count == 1, "truncation recovery failed"); for(var i=0;i<250;i++) File.AppendAllText(journal, Hook(",\"turnId\":\""+i+"\"}\n")); tailer.Poll(); Require(tailer.Snapshot().Count <= 200, "history exceeded bound");
    EventJournal.SetTestDirectoryPath(root); EventJournal.SetDetailedLoggingEnabled(false); EventJournal.Clear(); EventJournal.Append(new { timestampUtc=now, source="state_normalizer", @event="normalized_state_changed", previous="NORMAL", current="RUNNING", reason="codex_user_prompt_submit" }); EventJournal.Append(new { timestampUtc=now, source="state_normalizer", @event="session_state_changed", current="RUNNING", reason="codex_pre_tool_use", correlation=new { prompt="secret" } }); EventJournal.Append(new { timestampUtc=now, source="state_normalizer", @event="normalized_state_changed", previous="NORMAL", current="RUNNING", reason="secret" }); var lines=File.ReadAllLines(journal); Require(lines.Length==1, "detailed-off operational filtering was not strict");
} finally { EventJournal.SetTestDirectoryPath(null); if(Directory.Exists(root)) Directory.Delete(root,true); }
var old = JsonSerializer.Deserialize<StatusTraySnapshot>("{\"state\":\"NORMAL\",\"reason\":\"test\",\"stateSinceUtc\":\"2026-01-01T00:00:00Z\",\"session\":\"\",\"cwd\":\"\",\"rgbEnabled\":false,\"rgbStatus\":\"OFF\",\"notificationStatus\":\"\",\"detailedLogging\":false,\"hooksHealthy\":true,\"hooksStatus\":\"OK\",\"hooksDetail\":\"\",\"autostart\":false,\"configPath\":\"\",\"configSchema\":1}"); Require(old?.Sessions is null && old.RunningCount==0, "old IPC snapshot compatibility failed"); var current = new StatusTraySessionSnapshot("s","RUNNING",true,true,"C:\\work","th","tu",DateTimeOffset.UtcNow); Require(current.Cwd=="C:\\work" && current.ThreadId=="th" && current.TurnId=="tu", "session snapshot fields failed"); Require(LoopbackPolicy.IsLoopback("127.0.0.1") && !LoopbackPolicy.IsLoopback("0.0.0.0") && !LoopbackPolicy.IsLoopback("192.168.1.2"), "loopback policy failed"); var buffer=new SseClientBuffer(32); for(var i=0;i<100;i++) buffer.TryWrite(safe with { TurnId=i.ToString() }); var count=0; while(buffer.Reader.TryRead(out _)) count++; Require(count<=32, "SSE client queue was not bounded"); var poller=new SnapshotPoller(); await poller.PollAsync(); Require(!poller.Online && poller.Snapshot is null, "offline snapshot was not safe");
Console.WriteLine("REAL_BEHAVIOR_TESTS=PASS"); Console.WriteLine("SSE_BOUNDED=PASS"); Console.WriteLine("SSE_SLOW_CLIENT_TEST=PASS"); Console.WriteLine("JOURNAL_BEHAVIOR=PASS"); Console.WriteLine("IPC_SESSION_COMPAT=PASS"); Console.WriteLine("PRIVACY_FIXTURES=PASS"); Console.WriteLine("LOOPBACK_POLICY=PASS"); Console.WriteLine("TRAY_OFFLINE_SNAPSHOT_SAFE=PASS");
