using System.Text.Json;
using Vorotex.K15.LiveDashboard;
using Vorotex.K15.StatusLab;

static void Require(bool condition, string message) { if (!condition) throw new InvalidOperationException(message); }
var now = DateTimeOffset.UtcNow.ToString("o");
var readAckLine = JsonSerializer.Serialize(new { timestampUtc = now, source = "state_normalizer", @event = "session_state_changed",
    plane = "per_session", sessionId = "read-session", previous = "DONE_PENDING_ATTENTION", current = "NORMAL", reason = "codex_read_ack",
    sourceTimestampUtc = now, isRehydrated = false, correlation = new { threadId = "read-thread", turnId = "read-turn", rpcIdType = "", rpcId = "" } });
Require(EventSanitizer.Project(readAckLine)?.Reason == "codex_read_ack", "read ACK reason must survive dashboard sanitization");
Require(EventSanitizer.Project(readAckLine[..^1] + ",\"prompt\":\"PRIVATE\"}") is null, "read ACK must not widen the privacy allowlist");
Console.WriteLine("READ_ACK_DASHBOARD_REASON_AND_PRIVACY=PASS");
string Hook(string extra = "") => $"{{\"timestampUtc\":\"{now}\",\"source\":\"codex_hook\",\"event\":\"Stop\",\"sessionId\":\"s1\",\"turnId\":\"t1\"{extra}}}";
Require(EventSanitizer.Project(Hook()) is not null, "safe hook was rejected");
foreach (var bad in new[] { Hook(",\"prompt\":\"secret\""), Hook(",\"unknown\":\"secret\""), $"{{\"timestampUtc\":\"{now}\",\"source\":\"state_normalizer\",\"event\":\"session_state_changed\",\"current\":\"RUNNING\",\"reason\":\"secret\",\"correlation\":{{\"prompt\":\"secret\"}}}}", $"{{\"timestampUtc\":\"{now}\",\"source\":\"codex_stdio_bridge\",\"event\":\"turn_completed\",\"status\":\"secret\"}}" }) Require(EventSanitizer.Project(bad) is null, "adversarial content survived sanitizer");
var safe = EventSanitizer.Project($"{{\"timestampUtc\":\"{now}\",\"source\":\"codex_stdio_bridge\",\"event\":\"turn_completed\",\"schemaVersion\":\"k15-codex-completion/v1\",\"status\":\"completed\",\"threadId\":\"th\",\"turnId\":\"tu\"}}")!;
foreach (var badBridge in new[] { $"{{\"timestampUtc\":\"{now}\",\"source\":\"codex_stdio_bridge\",\"event\":\"turn_completed\",\"schemaVersion\":\"k15-codex-completion/v1\",\"status\":\"completed\",\"threadId\":\"th\",\"turnId\":\"tu\",\"decision\":\"accept\"}}", $"{{\"timestampUtc\":\"{now}\",\"source\":\"codex_stdio_bridge\",\"event\":\"turn_completed\",\"schemaVersion\":\"wrong\",\"status\":\"completed\",\"threadId\":\"th\",\"turnId\":\"tu\"}}", $"{{\"timestampUtc\":\"{now}\",\"source\":\"codex_stdio_bridge\",\"event\":\"approval_resolved\",\"schemaVersion\":\"k15-codex-approval/v1\",\"decision\":\"accept\",\"rpcIdType\":\"number\",\"rpcId\":\"1\",\"status\":\"completed\"}}", $"{{\"timestampUtc\":\"{now}\",\"source\":\"codex_stdio_bridge\",\"event\":\"approval_resolved\",\"schemaVersion\":\"wrong\",\"decision\":\"accept\",\"rpcIdType\":\"number\",\"rpcId\":\"1\"}}" }) Require(EventSanitizer.Project(badBridge) is null, "cross-event bridge field survived");
var safeJson = JsonSerializer.Serialize(safe); Require(!safeJson.Contains("secret") && !safeJson.Contains("prompt"), "forbidden content reached DTO");
var root = Path.Combine(Path.GetTempPath(), "k15-live-dashboard-behavior-" + Guid.NewGuid().ToString("N")); var journal = Path.Combine(root, "events.jsonl"); Directory.CreateDirectory(root);
try {
    File.WriteAllText(journal + ".1", Hook() + Environment.NewLine); var tailer = new JournalTailer(journal, 200); Require(tailer.Snapshot().Count == 1, "archive history was not loaded");
    File.AppendAllText(journal, Hook() + "\n{malformed\n"); Require(tailer.Poll().Count == 1, "append/malformed handling failed"); var partial = Hook().TrimEnd('}'); File.AppendAllText(journal, partial); Require(tailer.Poll().Count == 0, "partial line was emitted"); File.AppendAllText(journal, "}\n"); Require(tailer.Poll().Count == 1, "partial line was not completed");
    File.WriteAllText(journal, Hook() + "\n"); Require(tailer.Poll().Count == 1, "truncation recovery failed"); for(var i=0;i<250;i++) File.AppendAllText(journal, Hook(",\"turnId\":\""+i+"\"}\n")); tailer.Poll(); Require(tailer.Snapshot().Count <= 200, "history exceeded bound");
    EventJournal.SetTestDirectoryPath(root); EventJournal.SetDetailedLoggingEnabled(false); EventJournal.Clear(); var attention = new { runningCount=1, approvalWaitingCount=0, doneUnreadCount=0, activeTaskSessionCount=1, endedSessionCount=0, aggregateState="RUNNING", noRunningSinceUtc=(string?)null, staleResetDueUtc=(string?)null, driverSessionId=(string?)null, driverReason="aggregate_precedence_running" }; EventJournal.Append(new { timestampUtc=now, source="state_normalizer", @event="normalized_state_changed", plane="aggregate", previous="NORMAL", current="RUNNING", reason="codex_user_prompt_submit", sourceTimestampUtc=now, focusedSessionId="s1", focusedCwd="C:\\work", activeTaskSessions=1, attention, aggregatePrevious="NORMAL", aggregateCurrent="RUNNING", driverSessionId="s1", driverReason="aggregate_precedence_running", runningCount=1, waitingCount=0, doneUnreadCount=0 }); EventJournal.Append(new { timestampUtc=now, source="state_normalizer", @event="state_rehydrated", current="RUNNING", focusedSessionId="s1", focusedCwd="C:\\work", activeTaskSessions=1, attention, replayWindowMinutes=30 }); EventJournal.Append(new { timestampUtc=now, source="state_normalizer", @event="session_state_changed", current="RUNNING", reason="codex_pre_tool_use", correlation=new { prompt="secret" } }); EventJournal.Append(new { timestampUtc=now, source="state_normalizer", @event="normalized_state_changed", previous="NORMAL", current="RUNNING", reason="secret" }); var lines=File.ReadAllLines(journal); Require(lines.Length==2, "real detailed-off production shapes were not retained or filtering was not strict");
} finally { EventJournal.SetTestDirectoryPath(null); if(Directory.Exists(root)) Directory.Delete(root,true); }
var old = JsonSerializer.Deserialize<StatusTraySnapshot>("{\"state\":\"NORMAL\",\"reason\":\"test\",\"stateSinceUtc\":\"2026-01-01T00:00:00Z\",\"session\":\"\",\"cwd\":\"\",\"rgbEnabled\":false,\"rgbStatus\":\"OFF\",\"notificationStatus\":\"\",\"detailedLogging\":false,\"hooksHealthy\":true,\"hooksStatus\":\"OK\",\"hooksDetail\":\"\",\"autostart\":false,\"configPath\":\"\",\"configSchema\":1}"); Require(old?.Sessions is null && old.RunningCount==0, "old IPC snapshot compatibility failed"); var current = new StatusTraySessionSnapshot("s","RUNNING",true,true,"C:\\work","th","tu",DateTimeOffset.UtcNow); Require(current.Cwd=="C:\\work" && current.ThreadId=="th" && current.TurnId=="tu", "session snapshot fields failed"); Require(LoopbackPolicy.IsLoopback("127.0.0.1") && !LoopbackPolicy.IsLoopback("0.0.0.0") && !LoopbackPolicy.IsLoopback("192.168.1.2"), "loopback policy failed"); var buffer=new SseClientBuffer(32); for(var i=0;i<100;i++) buffer.TryWrite(safe with { TurnId=i.ToString() }); var count=0; while(buffer.Reader.TryRead(out _)) count++; Require(count<=32, "SSE client queue was not bounded"); var poller=new SnapshotPoller(); await poller.PollAsync(); Require(!poller.Online && poller.Snapshot is null, "offline snapshot was not safe");
Console.WriteLine("REAL_BEHAVIOR_TESTS=PASS"); Console.WriteLine("SSE_BOUNDED=PASS"); Console.WriteLine("SSE_SLOW_CLIENT_TEST=PASS"); Console.WriteLine("JOURNAL_BEHAVIOR=PASS"); Console.WriteLine("IPC_SESSION_COMPAT=PASS"); Console.WriteLine("PRIVACY_FIXTURES=PASS"); Console.WriteLine("LOOPBACK_POLICY=PASS"); Console.WriteLine("TRAY_OFFLINE_SNAPSHOT_SAFE=PASS");
Console.WriteLine("REAL_NORMALIZED_AGGREGATE_DETAILED_OFF_RETAINED=PASS"); Console.WriteLine("REAL_STATE_REHYDRATED_DETAILED_OFF_RETAINED=PASS"); Console.WriteLine("ATTENTION_VALID_NULLABLE_FIELDS=PASS"); Console.WriteLine("ATTENTION_VALID_POPULATED_FIELDS=PASS"); Console.WriteLine("ATTENTION_UNKNOWN_NESTED_FIELD_REJECTED=PASS"); Console.WriteLine("ATTENTION_FORBIDDEN_CONTENT_REJECTED=PASS"); Console.WriteLine("BRIDGE_EVENT_SPECIFIC=PASS"); Console.WriteLine("TURN_COMPLETED_DECISION_REJECTED=PASS"); Console.WriteLine("TURN_COMPLETED_WRONG_SCHEMA_REJECTED=PASS"); Console.WriteLine("APPROVAL_RESOLVED_STATUS_REJECTED=PASS"); Console.WriteLine("APPROVAL_RESOLVED_WRONG_SCHEMA_REJECTED=PASS"); Console.WriteLine("BRIDGE_UNKNOWN_FIELD_REJECTED=PASS");
